import { expect, test } from '@playwright/test'
import { mockConvex } from './convex-fixture'

const keeper = { rank: 1, username: 'EmberKeeper', durationMs: 65125, achievedAt: 1 }

test('receives new records and discovers releases without refresh', async ({ page }) => {
  const server = await mockConvex(page)
  await page.goto('/')
  await expect(page.getByText('No lights recorded yet.', { exact: false })).toBeVisible()
  server.publish({ '0.1.0': [keeper] })
  await expect(page.getByLabel('Game version')).toHaveValue('0.1.0')
  await expect(page.getByRole('cell', { name: '01:05.125' })).toBeVisible()
  server.publish({ '0.1.0': [{ ...keeper, durationMs: 85001 }], '0.2.0': [{ ...keeper, username: 'NewRelease' }] })
  await expect(page.getByRole('cell', { name: '01:25.001' })).toBeVisible()
  await expect(page.getByLabel('Game version').locator('option')).toHaveText(['v0.1.0', 'v0.2.0'])
  await expect(page.getByLabel('Game version')).toHaveValue('0.1.0')
  await expect(page.getByRole('button', { name: 'Refresh' })).toHaveCount(0)
})

test('deep links to empty releases and switches the active subscription', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const server = await mockConvex(page, { '0.1.0': [keeper] })
  await page.goto('/?version=0.3.0')
  await expect(page.getByText('No lights recorded for v0.3.0 yet.', { exact: false })).toBeVisible()
  await page.getByLabel('Game version').selectOption('0.1.0')
  await expect(page.getByRole('cell', { name: 'EmberKeeper' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('leaderboard.png'), fullPage: true })
  await expect.poll(() => server.subscriptions().filter(query => query.udfPath.endsWith(':list')).map(query => query.args[0]?.version)).toEqual(['0.1.0'])
  server.publish({ '0.1.0': [keeper], '0.3.0': [{ ...keeper, username: 'OtherVersion' }] })
  await expect(page.getByRole('cell', { name: 'OtherVersion' })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('recovers after a subscription error', async ({ page }) => {
  const server = await mockConvex(page, { '0.1.0': [keeper] })
  server.fail(true)
  await page.goto('/?version=0.1.0')
  await expect.poll(() => server.subscriptions().length).toBe(2)
  await expect(page.getByText('We couldn’t reach the leaderboard.', { exact: false })).toBeVisible()
  server.fail(false)
  await expect(page.getByRole('cell', { name: 'EmberKeeper' })).toBeVisible()
})

test('shows run energy and the saved turret pattern, including live updates and legacy runs', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const turretLayout = { width: 960, height: 720, turrets: [{ x: 0.25, y: 0.4 }, { x: 0.75, y: 0.6 }], upgrades: { damage: 2, fireRate: 1, health: 1 } }
  const detailed = { ...keeper, energyEarned: 125.75, energyInvested: 290, turretLayout }
  const legacy = { ...keeper, rank: 2, username: 'OlderKeeper', totalEnergy: 5000 }
  const server = await mockConvex(page, { '0.1.0': [detailed, legacy] })
  await page.goto('/?version=0.1.0')
  await expect(page.getByLabel('Energy earned: 125', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Defense investment: 290', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Defense investment: Not recorded', { exact: true })).toBeVisible()
  await expect(page.getByText('5,000', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Turret layout not recorded', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Energy earned: Not recorded', { exact: true })).toBeVisible()
  const toggle = page.getByLabel("View EmberKeeper's turret layout")
  await toggle.focus()
  await page.keyboard.press('Enter')
  const diagram = page.getByRole('img', { name: "EmberKeeper's run layout: 2 turrets", exact: true })
  await expect(diagram).toBeVisible()
  await expect(page.getByText('Upgrades · Damage level 2 · Fire rate level 1 · Health level 1', { exact: true })).toBeVisible()
  await expect(diagram).toHaveAttribute('viewBox', '0 0 960 720')
  await expect(diagram.locator('g')).toHaveCount(2)
  await expect(diagram.locator('g').first()).toHaveAttribute('transform', 'translate(240 288)')
  await expect(diagram.locator('g').last()).toHaveAttribute('transform', 'translate(720 432)')
  await expect(page.getByText('2 Type not recorded', { exact: true })).toBeVisible()
  server.publish({ '0.1.0': [{ ...detailed, turretLayout: { ...turretLayout, turrets: [{ x: 0.25, y: 0.4, type: 'damage' }, { x: 0.75, y: 0.6, type: 'pulse' }] } }, legacy] })
  await expect(page.getByText('1 Damage', { exact: true })).toBeVisible()
  await expect(page.getByText('1 Slow', { exact: true })).toBeVisible()
  await expect(page.getByText('2 Type not recorded', { exact: true })).toHaveCount(0)
  await expect(diagram.locator('g').last().locator('path')).toHaveAttribute('fill', '#d3a4ff')
  await expect(diagram.locator('g').first().locator('circle').last()).toHaveAttribute('fill', '#9bddff')
  server.publish({ '0.1.0': [{ ...detailed, turretLayout: { ...turretLayout, turrets: [{ x: 0.25, y: 0.4, type: 'damage' }, { x: 0.75, y: 0.6, type: 'pulse' }, { x: 0.5, y: 0.2, type: 'sniper' }] } }, legacy] })
  const sniperDiagram = page.getByRole('img', { name: "EmberKeeper's run layout: 3 turrets", exact: true })
  await expect(sniperDiagram).toBeVisible()
  await expect(page.getByText('1 Watchlight', { exact: true })).toBeVisible()
  await expect(sniperDiagram.locator('g').last().locator('title')).toHaveText('Watchlight sniper')
  await expect(sniperDiagram.locator('g').last().locator('rect').last()).toHaveAttribute('fill', '#fff0cc')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('run-details.png'), fullPage: true })
  server.publish({ '0.1.0': [{ ...detailed, energyEarned: 0, energyInvested: 0, turretLayout: { width: 720, height: 960, turrets: [] } }, legacy] })
  await expect(page.getByLabel('Energy earned: 0', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Defense investment: 0', { exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: "EmberKeeper's run layout: 0 turrets", exact: true })).toHaveAttribute('viewBox', '0 0 720 960')
  await expect(page.getByText('0 turrets · Positions at run end · Arena center marked', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
